import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./components/header";
import Footer from "./components/footer";
import BackToTop from "./components/BackToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chelsea Effendi - Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}
      style={{ background: "#0f0a1e", color: "white" }}
      >       {/* Bg lokal biar semua page otomatis gelap */}
        {/* Header & Footer muncul di semua halaman */}
        <Header />
        <main style={{ paddingTop: "80px" }}> {/* biar g ketiban header*/}
          {children}
        </main>
        <Footer />
        {/* Floating Button - Global */}
        <BackToTop />
      </body>
    </html>
  );
}
